-- INSERT INSTO voiceCarbo.alimento VALUES (Nome, Medida, Peso, Kcal, Carboidratos, Grupo);
INSERT INTO voiceCarbo.alimento VALUES ('aipim cozido', 'pedaço médio', 100.0, 120.0, 29.0, 'Amido');
INSERT INTO voiceCarbo.alimento VALUES ('arroz branco', '1 colher de sopa', 20.0, 26.0, 5.0, 'Amido');
INSERT INTO voiceCarbo.alimento VALUES ('arroz integral', '1 colher de sopa', 20.0, 25.0, 5.0, 'Amido');
INSERT INTO voiceCarbo.alimento VALUES ('arroz carreteiro', '1 colher de sopa', 25.0, 38.0, 5.0, 'Amido');
INSERT INTO voiceCarbo.alimento VALUES ('arroz à grega', '1 colher de sopa', 25.0, 35.0, 7.0, 'Amido');
INSERT INTO voiceCarbo.alimento VALUES ('batata baroa', '1 colher de sopa', 35.0, 44.0, 10.0, 'Amido');
INSERT INTO voiceCarbo.alimento VALUES ('batata-doce', '1 colher de sopa', 42.0, 43.0, 10.0, 'Amido');
INSERT INTO voiceCarbo.alimento VALUES ('batata inglesa cozida', '1 colher de sopa', 30.0, 26.0, 6.0, 'Amido');
INSERT INTO voiceCarbo.alimento VALUES ('batata inglesa frita', '1 colher de sopa', 15.0, 42.0, 5.0, 'Amido');
INSERT INTO voiceCarbo.alimento VALUES ('batata palha', '1 colher de servir', 13.0, 23.0, 2.0, 'Amido');
INSERT INTO voiceCarbo.alimento VALUES ('canjica', '1 concha média', 120.0, 136.0, 23.0, 'Amido');
INSERT INTO voiceCarbo.alimento VALUES ('cará cozido', '1 colher de sopa', 25.0, 29.0, 7.0, 'Amido');
INSERT INTO voiceCarbo.alimento VALUES ('cuscuz de milho', 'pedaço pequeno', 85.0, 161.0, 34.0, 'Amido');
INSERT INTO voiceCarbo.alimento VALUES ('inhame cozido', 'pedaço pequeno', 22.0, 25.0, 6.0, 'Amido');
INSERT INTO voiceCarbo.alimento VALUES ('mandioca cozida', '1 colher de sopa', 30.0, 37.0, 9.0, 'Amido');
INSERT INTO voiceCarbo.alimento VALUES ('milho cozido', '1 colher de sopa', 24.0, 30.0, 6.0, 'Amido');
INSERT INTO voiceCarbo.alimento VALUES ('milho em espiga com manteiga', 'unidade', 100.0, 233.0, 32.0, 'Amido');
INSERT INTO voiceCarbo.alimento VALUES ('milho verde enlatado', '1 colher de sopa', 24.0, 23.0, 5.0, 'Amido');
INSERT INTO voiceCarbo.alimento VALUES ('polenta', '1 colher de sopa', 35.0, 36.0, 8.0, 'Amido');
INSERT INTO voiceCarbo.alimento VALUES ('purê de batata', '1 colher de sopa', 45.0, 56.0, 8.0, 'Amido');
INSERT INTO voiceCarbo.alimento VALUES ('amido de arroz', '1 colher de sopa cheia', 20.0, 70.0, 17.0, 'Farinha');
INSERT INTO voiceCarbo.alimento VALUES ('amido de milho', '1 colher de sopa cheia', 20.0, 69.0, 17.0, 'Farinha');
INSERT INTO voiceCarbo.alimento VALUES ('arroz, flocos instantâneo', '1 colher de sopa cheia', 14.0, 49.0, 11.0, 'Farinha');
INSERT INTO voiceCarbo.alimento VALUES ('aveia (farinha)', '1 colher de sopa cheia', 18.0, 71.0, 12.0, 'Farinha');
INSERT INTO voiceCarbo.alimento VALUES ('aveia (flocos)', '1 colher de sopa cheia', 15.0, 9.0, 2.0, 'Farinha');
INSERT INTO voiceCarbo.alimento VALUES ('farinha de arroz', '1 colher de sopa cheia', 17.0, 60.0, 14.0, 'Farinha');
INSERT INTO voiceCarbo.alimento VALUES ('farinha de mandioca', '1 colher de sopa cheia', 16.0, 57.0, 14.0, 'Farinha');
INSERT INTO voiceCarbo.alimento VALUES ('farinha de milho', '1 colher de sopa cheia', 15.0, 54.0, 12.0, 'Farinha');
INSERT INTO voiceCarbo.alimento VALUES ('farinha de milho integral', '1 colher de sopa cheia', 15.0, 53.0, 11.0, 'Farinha');
INSERT INTO voiceCarbo.alimento VALUES ('farinha de rosca', '1 colher de sopa cheia', 15.0, 61.0, 11.0, 'Farinha');
INSERT INTO voiceCarbo.alimento VALUES ('farofa de farinha de mandioca', '1 colher de sopa cheia', 25.0, 96.0, 20.0, 'Farinha');
INSERT INTO voiceCarbo.alimento VALUES ('farofa pronta (yoki®)', '1 colher de sopa', 18.0, 75.0, 15.0, 'Farinha');
INSERT INTO voiceCarbo.alimento VALUES ('farinha de soja', '1 colher de sopa', 15.0, 65.0, 5.0, 'Farinha');
INSERT INTO voiceCarbo.alimento VALUES ('farinha de trigo', '1 colher de sopa', 20.0, 71.0, 15.0, 'Farinha');
INSERT INTO voiceCarbo.alimento VALUES ('fécula de batata', '1 colher de sopa', 20.0, 66.0, 16.0, 'Farinha');
INSERT INTO voiceCarbo.alimento VALUES ('fubá', '1 colher de sopa cheia', 20.0, 71.0, 16.0, 'Farinha');
INSERT INTO voiceCarbo.alimento VALUES ('farinha de linhaça', '1 colher de sopa cheia', 12.0, 32.0, 1.0, 'Farinha');
INSERT INTO voiceCarbo.alimento VALUES ('polvilho', '1 colher de sopa cheia', 16.0, 56.0, 14.0, 'Farinha');
INSERT INTO voiceCarbo.alimento VALUES ('espaguete ao sugo', 'escumadeira', 110.0, 112.0, 24.0, 'Massas');
INSERT INTO voiceCarbo.alimento VALUES ('macarrão à bolonhesa', 'escumadeira cheia', 110.0, 136.0, 22.0, 'Massas');
INSERT INTO voiceCarbo.alimento VALUES ('macarrão caseiro cozido', '1 colher de arroz cheia', 50.0, 54.0, 11.0, 'Massas');
INSERT INTO voiceCarbo.alimento VALUES ('macarrão instantâneo*', 'pacote', 80.0, 370.0, 50.0, 'Massas');
INSERT INTO voiceCarbo.alimento VALUES ('massa de pastel pronta', '2 discos de massa', 30.0, 83.0, 16.0, 'Massas');
INSERT INTO voiceCarbo.alimento VALUES ('panqueca com carne', 'unidade média', 80.0, 229.0, 18.0, 'Massas');
INSERT INTO voiceCarbo.alimento VALUES ('panqueca com frango', 'unidade pequena', 60.0, 120.0, 12.0, 'Massas');
INSERT INTO voiceCarbo.alimento VALUES ('lasanha com frango', 'porção média', 325.0, 441.0, 36.0, 'Massas');
INSERT INTO voiceCarbo.alimento VALUES ('lasanha de peito de peru com queijos', 'porção média', 325.0, 456.0, 48.0, 'Massas');
INSERT INTO voiceCarbo.alimento VALUES ('lasanha à bolonhesa', 'escumadeira', 170.0, 355.0, 27.0, 'Massas');
INSERT INTO voiceCarbo.alimento VALUES ('nhoque', 'escumadeira cheia', 100.0, 120.0, 21.0, 'Massas');
INSERT INTO voiceCarbo.alimento VALUES ('yakissoba de frango (light)', 'porção', 120.0, 311.0, 27.0, 'Massas');
INSERT INTO voiceCarbo.alimento VALUES ('yakissoba com frango e gado', 'porção média', 225.0, 227.0, 38.0, 'Massas');
INSERT INTO voiceCarbo.alimento VALUES ('pão caseiro', 'fatia', 50.0, 176.0, 32.0, 'Pães');
INSERT INTO voiceCarbo.alimento VALUES ('pão de batata-doce', 'unidade', 50.0, 136.0, 26.0, 'Pães');
INSERT INTO voiceCarbo.alimento VALUES ('pão de forma', 'unidade', 25.0, 62.0, 12.0, 'Pães');
INSERT INTO voiceCarbo.alimento VALUES ('pão de forma light', 'fatia', 25.0, 50.0, 8.0, 'Pães');
INSERT INTO voiceCarbo.alimento VALUES ('pão de hamburguer', 'unidade', 70.0, 188.0, 40.0, 'Pães');
INSERT INTO voiceCarbo.alimento VALUES ('pão de leite', 'unidade', 54.0, 149.0, 30.0, 'Pães');
INSERT INTO voiceCarbo.alimento VALUES ('pão de queijo', 'unidade pequena', 20.0, 87.0, 9.0, 'Pães');
INSERT INTO voiceCarbo.alimento VALUES ('pão francês', 'unidade', 50.0, 135.0, 28.0, 'Pães');
INSERT INTO voiceCarbo.alimento VALUES ('pão italiano', 'fatia média', 50.0, 125.0, 28.0, 'Pães');
INSERT INTO voiceCarbo.alimento VALUES ('pão sírio pita bread®', 'unidade média', 58.0, 158.0, 33.0, 'Pães');
INSERT INTO voiceCarbo.alimento VALUES ('pão sovado', 'fatia', 50.0, 155.0, 31.0, 'Pães');
INSERT INTO voiceCarbo.alimento VALUES ('pão tipo hot dog', 'unidade', 55.0, 150.0, 29.0, 'Pães');
INSERT INTO voiceCarbo.alimento VALUES ('pão tipo bisnaguinha', 'unidade', 20.0, 60.0, 11.0, 'Pães');
INSERT INTO voiceCarbo.alimento VALUES ('bolo de aipim com coco', 'fatia média', 80.0, 243.0, 37.0, 'Bolos');
INSERT INTO voiceCarbo.alimento VALUES ('bolo de baunilha', 'fatia', 40.0, 164.0, 22.0, 'Bolos');
INSERT INTO voiceCarbo.alimento VALUES ('bolo de banana', 'fatia média', 70.0, 211.0, 33.0, 'Bolos');
INSERT INTO voiceCarbo.alimento VALUES ('bolo de cenoura', 'fatia média', 60.0, 227.0, 38.0, 'Bolos');
INSERT INTO voiceCarbo.alimento VALUES ('bolo de chuva', 'unidade pequena', 20.0, 54.0, 8.0, 'Bolos');
INSERT INTO voiceCarbo.alimento VALUES ('bolo de laranja', 'fatia média', 60.0, 275.0, 31.0, 'Bolos');
INSERT INTO voiceCarbo.alimento VALUES ('bolo de festa simples', 'fatia média', 100.0, 320.0, 54.0, 'Bolos');
INSERT INTO voiceCarbo.alimento VALUES ('bolo de milho', 'fatia média', 100.0, 290.0, 54.0, 'Bolos');
INSERT INTO voiceCarbo.alimento VALUES ('bolo mesclado', 'fatia média', 60.0, 200.0, 30.0, 'Bolos');
INSERT INTO voiceCarbo.alimento VALUES ('brownie', 'unidade pequena', 40.0, 180.0, 25.0, 'Bolos');
INSERT INTO voiceCarbo.alimento VALUES ('brownie diet', 'unidade pequena', 40.0, 95.0, 11.0, 'Bolos');
INSERT INTO voiceCarbo.alimento VALUES ('croissant', 'unidade grande', 80.0, 328.0, 32.0, 'Bolos');
INSERT INTO voiceCarbo.alimento VALUES ('panetone de frutas', 'fatia pequena', 25.0, 88.0, 14.0, 'Bolos');
INSERT INTO voiceCarbo.alimento VALUES ('torta de limão', 'fatia pequena', 90.0, 217.0, 34.0, 'Tortas');
INSERT INTO voiceCarbo.alimento VALUES ('torta holandesa', 'porção pequena', 60.0, 181.0, 22.0, 'Tortas');
INSERT INTO voiceCarbo.alimento VALUES ('biscoito água e sal', 'unidade', 8.0, 34.0, 5.0, 'Biscoitos');
INSERT INTO voiceCarbo.alimento VALUES ('biscoito amanteigado', 'unidade', 7.0, 29.0, 5.0, 'Biscoitos');
INSERT INTO voiceCarbo.alimento VALUES ('biscoito champanhe', 'unidade', 8.0, 32.0, 6.0, 'Biscoitos');
INSERT INTO voiceCarbo.alimento VALUES ('biscoito cream crack', 'unidade', 7.0, 29.0, 5.0, 'Biscoitos');
INSERT INTO voiceCarbo.alimento VALUES ('biscoito de aveia e mel', 'unidade', 6.0, 29.0, 4.0, 'Biscoitos');
INSERT INTO voiceCarbo.alimento VALUES ('biscoito bono chocolate (nestlé®)', 'unidade', 10.0, 46.0, 6.0, 'Biscoitos');
INSERT INTO voiceCarbo.alimento VALUES ('biscoitos cookies®', 'unidade', 10.0, 47.0, 7.0, 'Biscoitos');
INSERT INTO voiceCarbo.alimento VALUES ('biscoito club social® integral', 'pacotinho', 28.0, 130.0, 17.0, 'Biscoitos');
INSERT INTO voiceCarbo.alimento VALUES ('biscoito de leite (nestle®)', 'unidade', 8.0, 38.0, 5.0, 'Biscoitos');
INSERT INTO voiceCarbo.alimento VALUES ('biscoito maisena (nestlé®)', 'unidade', 5.0, 22.0, 4.0, 'Biscoitos');
INSERT INTO voiceCarbo.alimento VALUES ('biscoito maria (nestlé®)', 'unidade', 6.0, 26.0, 4.0, 'Biscoitos');
INSERT INTO voiceCarbo.alimento VALUES ('biscoito passatempo® sem recheio', 'unidade', 6.0, 22.0, 4.0, 'Biscoitos');
INSERT INTO voiceCarbo.alimento VALUES ('biscoito passatempo® recheado', 'unidade', 12.0, 58.0, 8.0, 'Biscoitos');
INSERT INTO voiceCarbo.alimento VALUES ('biscoito de polvilho', 'unidade', 3.0, 12.0, 2.0, 'Biscoitos');
INSERT INTO voiceCarbo.alimento VALUES ('biscoito recheado*', 'unidade', 16.0, 75.0, 12.0, 'Biscoitos');
INSERT INTO voiceCarbo.alimento VALUES ('biscoito recheado* diet', 'unidade', 10.0, 40.0, 7.0, 'Biscoitos');
INSERT INTO voiceCarbo.alimento VALUES ('aveia flocos instantâneo', '1 colher de sopa', 14.0, 49.0, 11.0, 'Cereais');
INSERT INTO voiceCarbo.alimento VALUES ('granola', '1 colher de sopa cheia', 11.0, 51.0, 7.0, 'Cereais');
INSERT INTO voiceCarbo.alimento VALUES ('farinha láctea (nestlé®)', '1 colher de sopa rasa', 8.0, 30.0, 6.0, 'Cereais');
INSERT INTO voiceCarbo.alimento VALUES ('linhaça', '1 colher de sopa cheia', 15.0, 61.0, 1.0, 'Cereais');
INSERT INTO voiceCarbo.alimento VALUES ('mucilon de arroz®', '1 colher de sopa cheia', 9.0, 34.0, 8.0, 'Cereais');
INSERT INTO voiceCarbo.alimento VALUES ('mucilon de milho®', '1 colher de sopa cheia', 9.0, 34.0, 8.0, 'Cereais');
INSERT INTO voiceCarbo.alimento VALUES ('abacaxi', 'fatia média', 75.0, 44.0, 10.0, 'Frutas');
INSERT INTO voiceCarbo.alimento VALUES ('ameixa vermelha', 'unidade grande', 100.0, 55.0, 13.0, 'Frutas');
INSERT INTO voiceCarbo.alimento VALUES ('ameixa preta seca', 'unidade média', 5.0, 13.0, 3.0, 'Frutas');
INSERT INTO voiceCarbo.alimento VALUES ('banana-maça', 'unidade média', 65.0, 72.0, 15.0, 'Frutas');
INSERT INTO voiceCarbo.alimento VALUES ('banana-ouro', 'unidade pequena', 40.0, 42.0, 9.0, 'Frutas');
INSERT INTO voiceCarbo.alimento VALUES ('banana-prata', 'unidade média', 50.0, 49.0, 13.0, 'Frutas');
INSERT INTO voiceCarbo.alimento VALUES ('banana-da-terra', '1/2 unidade', 31.0, 36.0, 8.0, 'Frutas');
INSERT INTO voiceCarbo.alimento VALUES ('cajú', 'unidade grande', 100.0, 43.0, 10.0, 'Frutas');
INSERT INTO voiceCarbo.alimento VALUES ('caqui', 'unidade média', 110.0, 95.0, 22.0, 'Frutas');
INSERT INTO voiceCarbo.alimento VALUES ('fruta-do-conde', 'unidade pequena', 60.0, 41.0, 8.0, 'Frutas');
INSERT INTO voiceCarbo.alimento VALUES ('goiaba', 'unidade média', 170.0, 96.0, 20.0, 'Frutas');
INSERT INTO voiceCarbo.alimento VALUES ('graviola', 'porção', 100.0, 62.0, 16.0, 'Frutas');
INSERT INTO voiceCarbo.alimento VALUES ('jaca', 'bago médio', 12.0, 3.0, 1.0, 'Frutas');
INSERT INTO voiceCarbo.alimento VALUES ('kiwi', 'unidade média', 76.0, 51.0, 11.0, 'Frutas');
INSERT INTO voiceCarbo.alimento VALUES ('laranja', 'unidade média', 180.0, 93.0, 21.0, 'Frutas');
INSERT INTO voiceCarbo.alimento VALUES ('laranja lima', 'unidade média', 90.0, 41.0, 10.0, 'Frutas');
INSERT INTO voiceCarbo.alimento VALUES ('limão', 'unidade média', 15.0, 7.0, 1.0, 'Frutas');
INSERT INTO voiceCarbo.alimento VALUES ('maça com casca', 'unidade pequena', 90.0, 58.0, 14.0, 'Frutas');
INSERT INTO voiceCarbo.alimento VALUES ('mamão papaya', 'meia unidade', 160.0, 64.0, 16.0, 'Frutas');
INSERT INTO voiceCarbo.alimento VALUES ('manga espada', 'unidade média', 140.0, 91.0, 22.0, 'Frutas');
INSERT INTO voiceCarbo.alimento VALUES ('maracujá', 'unidade média', 45.0, 31.0, 6.0, 'Frutas');
INSERT INTO voiceCarbo.alimento VALUES ('melancia', 'fatia média', 200.0, 48.0, 11.0, 'Frutas');
INSERT INTO voiceCarbo.alimento VALUES ('melão', 'fatia grande', 115.0, 32.0, 7.0, 'Frutas');
INSERT INTO voiceCarbo.alimento VALUES ('morango', 'unidade média', 12.0, 5.0, 1.0, 'Frutas');
INSERT INTO voiceCarbo.alimento VALUES ('pêra crua', 'unidade média', 130.0, 80.0, 19.0, 'Frutas');
INSERT INTO voiceCarbo.alimento VALUES ('pêssego amarelo', 'unidade média', 60.0, 29.0, 6.0, 'Frutas');
INSERT INTO voiceCarbo.alimento VALUES ('romã', 'unidade', 150.0, 84.0, 23.0, 'Frutas');
INSERT INTO voiceCarbo.alimento VALUES ('salada de frutas', '1 colher de sopa cheia', 20.0, 10.0, 3.0, 'Frutas');
INSERT INTO voiceCarbo.alimento VALUES ('tangerina', 'unidade média', 135.0, 67.0, 15.0, 'Frutas');
INSERT INTO voiceCarbo.alimento VALUES ('tomate', 'fatia pequena', 10.0, 4.0, 1.0, 'Frutas');
INSERT INTO voiceCarbo.alimento VALUES ('uva comum', 'unidade', 8.0, 6.0, 1.0, 'Frutas');
INSERT INTO voiceCarbo.alimento VALUES ('abóbora cozida', '1 colher de sopa', 36.0, 25.0, 5.0, 'Hortaliças');
INSERT INTO voiceCarbo.alimento VALUES ('abobrinha cozida', '1 colher de sopa', 30.0, 3.0, 3.0, 'Hortaliças');
INSERT INTO voiceCarbo.alimento VALUES ('acelga/alface', 'folha média', 10.0, 2.0, 0.0, 'Hortaliças');
INSERT INTO voiceCarbo.alimento VALUES ('alho', '2 dentes', 10.0, 11.0, 3.0, 'Hortaliças');
INSERT INTO voiceCarbo.alimento VALUES ('berinjela cozida sem sal', '1 colher de sopa cheia', 25.0, 8.0, 2.0, 'Hortaliças');
INSERT INTO voiceCarbo.alimento VALUES ('beterraba cozida (picada)', '1 colher de sopa cheia', 20.0, 9.0, 2.0, 'Hortaliças');
INSERT INTO voiceCarbo.alimento VALUES ('beterraba crua', '1 colher de sopa cheia', 16.0, 7.0, 1.0, 'Hortaliças');
INSERT INTO voiceCarbo.alimento VALUES ('cebola crua (picada)', '1 colher de sopa cheia', 8.0, 2.0, 0.0, 'Hortaliças');
INSERT INTO voiceCarbo.alimento VALUES ('cenoura cozida', '1 colher de sopa cheia', 25.0, 8.0, 2.0, 'Hortaliças');
INSERT INTO voiceCarbo.alimento VALUES ('cenoura crua ralada', '1 colher de sopa cheia', 12.0, 4.0, 1.0, 'Hortaliças');
INSERT INTO voiceCarbo.alimento VALUES ('chuchu cozido', '1 colher de sopa', 20.0, 4.0, 1.0, 'Hortaliças');
INSERT INTO voiceCarbo.alimento VALUES ('couve-flor cozida', 'ramo médio', 60.0, 25.0, 4.0, 'Hortaliças');
INSERT INTO voiceCarbo.alimento VALUES ('espinafre refogado', '1 colher de sopa cheia', 25.0, 27.0, 2.0, 'Hortaliças');
INSERT INTO voiceCarbo.alimento VALUES ('jiló', '1 colher de sopa cheia', 60.0, 31.0, 5.0, 'Hortaliças');
INSERT INTO voiceCarbo.alimento VALUES ('moranga', '1 colher de sopa', 36.0, 7.0, 1.0, 'Hortaliças');
INSERT INTO voiceCarbo.alimento VALUES ('palmito em conserva', '1 colher de sopa cheia', 15.0, 3.0, 1.0, 'Hortaliças');
INSERT INTO voiceCarbo.alimento VALUES ('pepino', 'fatia pequena', 3.0, 1.0, 0.0, 'Hortaliças');
INSERT INTO voiceCarbo.alimento VALUES ('quiabo refogado', '1 colher de sopa', 40.0, 6.0, 2.0, 'Hortaliças');
INSERT INTO voiceCarbo.alimento VALUES ('rúcula', '1 prato de sobremesa', 100.0, 17.0, 2.0, 'Hortaliças');
INSERT INTO voiceCarbo.alimento VALUES ('repolho cozido', '1 colher de sopa cheia', 10.0, 1.0, 0.0, 'Hortaliças');
INSERT INTO voiceCarbo.alimento VALUES ('vagem cozida', '1 colher de sopa cheia', 20.0, 8.0, 2.0, 'Hortaliças');
INSERT INTO voiceCarbo.alimento VALUES ('coalhada', '1 colher de sopa', 30.0, 77.0, 2.0, 'Leite e derivados');
INSERT INTO voiceCarbo.alimento VALUES ('creme de leite', '1 colher de sopa rasa', 15.0, 46.0, 1.0, 'Leite e derivados');
INSERT INTO voiceCarbo.alimento VALUES ('creme de leite light', '1 colher de sopa', 15.0, 25.0, 0.0, 'Leite e derivados');
INSERT INTO voiceCarbo.alimento VALUES ('danoninho®', 'potinho', 45.0, 67.0, 8.0, 'Leite e derivados');
INSERT INTO voiceCarbo.alimento VALUES ('iogurte activia light®', 'pote', 100.0, 62.0, 11.0, 'Leite e derivados');
INSERT INTO voiceCarbo.alimento VALUES ('iogurte activia natural®', 'pote', 170.0, 132.0, 12.0, 'Leite e derivados');
INSERT INTO voiceCarbo.alimento VALUES ('iogurte natural com mel', 'copo', 200.0, 225.0, 36.0, 'Leite e derivados');
INSERT INTO voiceCarbo.alimento VALUES ('iogurte de frutas*', 'pote', 100.0, 90.0, 17.0, 'Leite e derivados');
INSERT INTO voiceCarbo.alimento VALUES ('iogurte molico zero açúcar®', 'potinho', 130.0, 68.0, 7.0, 'Leite e derivados');
INSERT INTO voiceCarbo.alimento VALUES ('leite de cabra integral', 'copo duplo cheio', 240.0, 223.0, 13.0, 'Leite e derivados');
INSERT INTO voiceCarbo.alimento VALUES ('leite condensado', '1 colher de sopa', 15.0, 49.0, 8.0, 'Leite e derivados');
INSERT INTO voiceCarbo.alimento VALUES ('leite condensado diet', '1 colher de sopa', 15.0, 41.0, 7.0, 'Leite e derivados');
INSERT INTO voiceCarbo.alimento VALUES ('leite de vaca desnatado', 'copo duplo cheio', 240.0, 84.0, 12.0, 'Leite e derivados');
INSERT INTO voiceCarbo.alimento VALUES ('leite de vaca semidesnatado', 'copo', 200.0, 96.0, 10.0, 'Leite e derivados');
INSERT INTO voiceCarbo.alimento VALUES ('leite de soja zero ades®', 'copo', 200.0, 59.0, 3.0, 'Leite e derivados');
INSERT INTO voiceCarbo.alimento VALUES ('leite em pó desnatado', '1 colher de sopa cheia', 10.0, 35.0, 5.0, 'Leite e derivados');
INSERT INTO voiceCarbo.alimento VALUES ('leite em pó integral', '1 colher de sopa cheia', 16.0, 80.0, 6.0, 'Leite e derivados');
INSERT INTO voiceCarbo.alimento VALUES ('queijo catupiry®', '1 colher de sopa', 30.0, 80.0, 0.0, 'Leite e derivados');
INSERT INTO voiceCarbo.alimento VALUES ('queijo cheddar', 'fatia', 25.0, 103.0, 0.0, 'Leite e derivados');
INSERT INTO voiceCarbo.alimento VALUES ('queijo cream cheese', '1 colher de sopa', 25.0, 85.0, 1.0, 'Leite e derivados');
INSERT INTO voiceCarbo.alimento VALUES ('queijo minas', 'fatia pequena', 30.0, 64.0, 1.0, 'Leite e derivados');
INSERT INTO voiceCarbo.alimento VALUES ('queijo mussarela', 'fatia média', 15.0, 42.0, 0.0, 'Leite e derivados');
INSERT INTO voiceCarbo.alimento VALUES ('queijo parmesão ralado', '1 colher de sopa', 5.0, 23.0, 0.0, 'Leite e derivados');
INSERT INTO voiceCarbo.alimento VALUES ('queijo polenguinho®', 'unidade', 20.0, 62.0, 1.0, 'Leite e derivados');
INSERT INTO voiceCarbo.alimento VALUES ('queijo prato', 'fatia média', 15.0, 60.0, 0.0, 'Leite e derivados');
INSERT INTO voiceCarbo.alimento VALUES ('queijo provolone', 'fatia média', 15.0, 51.0, 0.0, 'Leite e derivados');
INSERT INTO voiceCarbo.alimento VALUES ('queijo ricota', 'fatia média', 30.0, 54.0, 0.0, 'Leite e derivados');
INSERT INTO voiceCarbo.alimento VALUES ('requeijão cremoso', '1 colher de sopa cheia', 30.0, 106.0, 1.0, 'Leite e derivados');
INSERT INTO voiceCarbo.alimento VALUES ('requeijão cremoso light', '1 colher de sopa cheia', 30.0, 54.0, 1.0, 'Leite e derivados');
INSERT INTO voiceCarbo.alimento VALUES ('yakult®', 'unidade', 80.0, 50.0, 11.0, 'Leite e derivados');
INSERT INTO voiceCarbo.alimento VALUES ('acém magro cozido', 'pedaço médio', 100.0, 215.0, 0.0, 'Carnes, ovos e frios');
INSERT INTO voiceCarbo.alimento VALUES ('alcatra assada', 'pedaço médio', 100.0, 200.0, 0.0, 'Carnes, ovos e frios');
INSERT INTO voiceCarbo.alimento VALUES ('almôndega de carne', 'unidade média', 30.0, 65.0, 2.0, 'Carnes, ovos e frios');
INSERT INTO voiceCarbo.alimento VALUES ('atum em água enlatado', '1 colher de sopa', 20.0, 25.0, 0.0, 'Carnes, ovos e frios');
INSERT INTO voiceCarbo.alimento VALUES ('bacalhau cozido', 'escumadeira média', 60.0, 88.0, 0.0, 'Carnes, ovos e frios');
INSERT INTO voiceCarbo.alimento VALUES ('bacon', 'fatia média', 15.0, 99.0, 0.0, 'Carnes, ovos e frios');
INSERT INTO voiceCarbo.alimento VALUES ('bife de boi', 'pedaço médio', 100.0, 228.0, 0.0, 'Carnes, ovos e frios');
INSERT INTO voiceCarbo.alimento VALUES ('bife de frango', 'pedaço médio', 100.0, 227.0, 0.0, 'Carnes, ovos e frios');
INSERT INTO voiceCarbo.alimento VALUES ('caldo de carne knorr®', 'unidade', 9.0, 24.0, 2.0, 'Carnes, ovos e frios');
INSERT INTO voiceCarbo.alimento VALUES ('caldo de galinha knorr®', 'unidade', 9.0, 24.0, 1.0, 'Carnes, ovos e frios');
INSERT INTO voiceCarbo.alimento VALUES ('camarão cozido', 'unidade grande', 30.0, 27.0, 0.0, 'Carnes, ovos e frios');
INSERT INTO voiceCarbo.alimento VALUES ('camarão frito', '1 colher de sopa', 20.0, 37.0, 0.0, 'Carnes, ovos e frios');
INSERT INTO voiceCarbo.alimento VALUES ('carne assada', 'pedaço médio', 90.0, 259.0, 0.0, 'Carnes, ovos e frios');
INSERT INTO voiceCarbo.alimento VALUES ('carne de carneiro (lombo)', 'pedaço médio', 50.0, 181.0, 0.0, 'Carnes, ovos e frios');
INSERT INTO voiceCarbo.alimento VALUES ('carne de porco assada', 'pedaço médio', 90.0, 309.0, 0.0, 'Carnes, ovos e frios');
INSERT INTO voiceCarbo.alimento VALUES ('carne de porco cozida', 'pedaço médio', 90.0, 327.0, 0.0, 'Carnes, ovos e frios');
INSERT INTO voiceCarbo.alimento VALUES ('carne moída', '1 colher de sopa cheia', 25.0, 49.0, 0.0, 'Carnes, ovos e frios');
INSERT INTO voiceCarbo.alimento VALUES ('carne vegetal (soja)', '1 colher de sopa cheia', 25.0, 29.0, 2.0, 'Carnes, ovos e frios');
INSERT INTO voiceCarbo.alimento VALUES ('coração de frango', 'unidade média', 5.0, 7.0, 0.0, 'Carnes, ovos e frios');
INSERT INTO voiceCarbo.alimento VALUES ('fígado de boi frito', 'pedaço médio', 100.0, 210.0, 0.0, 'Carnes, ovos e frios');
INSERT INTO voiceCarbo.alimento VALUES ('filé de peixe grelhado', 'pedaço médio', 100.0, 180.0, 0.0, 'Carnes, ovos e frios');
INSERT INTO voiceCarbo.alimento VALUES ('frango à parmegiana', 'unidade', 120.0, 233.0, 23.0, 'Carnes, ovos e frios');
INSERT INTO voiceCarbo.alimento VALUES ('hamburguer assado', 'unidade média', 60.0, 104.0, 0.0, 'Carnes, ovos e frios');
INSERT INTO voiceCarbo.alimento VALUES ('mortadela', 'fatia média', 15.0, 41.0, 0.0, 'Carnes, ovos e frios');
INSERT INTO voiceCarbo.alimento VALUES ('nuggets de frango tradicional sadia®', 'unidade', 25.0, 53.0, 3.0, 'Carnes, ovos e frios');
INSERT INTO voiceCarbo.alimento VALUES ('ovo de galinha cozido', 'unidade média', 45.0, 71.0, 0.0, 'Carnes, ovos e frios');
INSERT INTO voiceCarbo.alimento VALUES ('presunto cozido', 'fatia média', 15.0, 22.0, 0.0, 'Carnes, ovos e frios');
INSERT INTO voiceCarbo.alimento VALUES ('salame', 'fatia média', 20.0, 59.0, 0.0, 'Carnes, ovos e frios');
INSERT INTO voiceCarbo.alimento VALUES ('salmão defumado', 'porção', 100.0, 233.0, 20.0, 'Carnes, ovos e frios');
INSERT INTO voiceCarbo.alimento VALUES ('salmão grelhado', '1 filé pequeno', 100.0, 171.0, 0.0, 'Carnes, ovos e frios');
INSERT INTO voiceCarbo.alimento VALUES ('salsicha comum', 'unidade média', 35.0, 116.0, 0.0, 'Carnes, ovos e frios');
INSERT INTO voiceCarbo.alimento VALUES ('sardinha enlatada no óleo', 'unidade média', 33.0, 65.0, 0.0, 'Carnes, ovos e frios');
INSERT INTO voiceCarbo.alimento VALUES ('amêndoa', 'unidade média', 3.0, 13.0, 1.0, 'Leguminosas');
INSERT INTO voiceCarbo.alimento VALUES ('amendoim (torrado e salgado)', '2 colheres de sopa', 34.0, 194.0, 5.0, 'Leguminosas');
INSERT INTO voiceCarbo.alimento VALUES ('castanha de caju', 'unidade média', 3.0, 13.0, 1.0, 'Leguminosas');
INSERT INTO voiceCarbo.alimento VALUES ('castanha-do-pará', 'unidade média', 6.0, 42.0, 1.0, 'Leguminosas');
INSERT INTO voiceCarbo.alimento VALUES ('ervilha em conserva', '1 colher de sopa cheia', 27.0, 20.0, 4.0, 'Leguminosas');
INSERT INTO voiceCarbo.alimento VALUES ('feijão carioquinha cozido', '1 colher de sopa cheia', 17.0, 19.0, 3.0, 'Leguminosas');
INSERT INTO voiceCarbo.alimento VALUES ('feijão preto cozido', '1 colher de sopa cheia', 17.0, 12.0, 2.0, 'Leguminosas');
INSERT INTO voiceCarbo.alimento VALUES ('grão-de-bico cozido', '1 colher de sopa cheia', 22.0, 25.0, 4.0, 'Leguminosas');
INSERT INTO voiceCarbo.alimento VALUES ('lentilha cozida', '1 colher de sopa cheia', 18.0, 19.0, 3.0, 'Leguminosas');
INSERT INTO voiceCarbo.alimento VALUES ('nozes', 'unidade média', 5.0, 35.0, 1.0, 'Leguminosas');
INSERT INTO voiceCarbo.alimento VALUES ('pistache', 'unidade', 1.0, 4.0, 0.0, 'Leguminosas');
INSERT INTO voiceCarbo.alimento VALUES ('soja cozida', '1 colher de sopa cheia', 17.0, 29.0, 2.0, 'Leguminosas');
INSERT INTO voiceCarbo.alimento VALUES ('pizza de calabresa', 'fatia média', 100.0, 240.0, 21.0, 'Lanches e Pizzas');
INSERT INTO voiceCarbo.alimento VALUES ('pizza de frango com catupiry', 'fatia média', 111.0, 274.0, 25.0, 'Lanches e Pizzas');
INSERT INTO voiceCarbo.alimento VALUES ('pizza portuguesa', 'fatia média', 125.0, 246.0, 24.0, 'Lanches e Pizzas');
INSERT INTO voiceCarbo.alimento VALUES ('pizza mussarela', 'fatia média', 100.0, 278.0, 22.0, 'Lanches e Pizzas');
INSERT INTO voiceCarbo.alimento VALUES ('pizza de frango com requeijão', 'fatia média', 77.0, 201.0, 23.0, 'Lanches e Pizzas');
INSERT INTO voiceCarbo.alimento VALUES ('pizza com peito de peru e ricota', 'fatia média', 70.0, 140.0, 19.0, 'Lanches e Pizzas');
INSERT INTO voiceCarbo.alimento VALUES ('pizza com presunto e champignon', 'fatia média', 58.0, 132.0, 15.0, 'Lanches e Pizzas');
INSERT INTO voiceCarbo.alimento VALUES ('pizza 4 queijos', 'fatia média', 100.0, 277.0, 27.0, 'Lanches e Pizzas');
INSERT INTO voiceCarbo.alimento VALUES ('american burguer*', 'unidade média', 177.0, 257.0, 22.0, 'Lanches e Pizzas');
INSERT INTO voiceCarbo.alimento VALUES ('acarajé', 'unidade média', 100.0, 282.0, 22.0, 'Lanches e Pizzas');
INSERT INTO voiceCarbo.alimento VALUES ('bolinha de queijo', 'unidade pequena', 10.0, 27.0, 3.0, 'Lanches e Pizzas');
INSERT INTO voiceCarbo.alimento VALUES ('bolinho de bacalhau', 'unidade média', 15.0, 42.0, 3.0, 'Lanches e Pizzas');
INSERT INTO voiceCarbo.alimento VALUES ('burritos de carne', 'unidade média', 100.0, 223.0, 19.0, 'Lanches e Pizzas');
INSERT INTO voiceCarbo.alimento VALUES ('burritos de frango', 'unidade média', 100.0, 204.0, 18.0, 'Lanches e Pizzas');
INSERT INTO voiceCarbo.alimento VALUES ('cachorro-quente simples', 'unidade', 125.0, 377.0, 29.0, 'Lanches e Pizzas');
INSERT INTO voiceCarbo.alimento VALUES ('coxinha frango (frita)', 'unidade (festa)', 10.0, 37.0, 4.0, 'Lanches e Pizzas');
INSERT INTO voiceCarbo.alimento VALUES ('croquete de carne', 'unidade pequena', 10.0, 35.0, 4.0, 'Lanches e Pizzas');
INSERT INTO voiceCarbo.alimento VALUES ('empada de frango', 'unidade média', 55.0, 197.0, 14.0, 'Lanches e Pizzas');
INSERT INTO voiceCarbo.alimento VALUES ('enroladinho de presunto e queijo', 'unidade média', 40.0, 114.0, 15.0, 'Lanches e Pizzas');
INSERT INTO voiceCarbo.alimento VALUES ('enroladinho de salsicha', 'unidade média', 27.0, 79.0, 3.0, 'Lanches e Pizzas');
INSERT INTO voiceCarbo.alimento VALUES ('esfirrra de carne', 'unidade média', 80.0, 203.0, 29.0, 'Lanches e Pizzas');
INSERT INTO voiceCarbo.alimento VALUES ('esfirrra de frango', 'unidade média', 80.0, 241.0, 20.0, 'Lanches e Pizzas');
INSERT INTO voiceCarbo.alimento VALUES ('misto quente', 'unidade', 85.0, 283.0, 29.0, 'Lanches e Pizzas');
INSERT INTO voiceCarbo.alimento VALUES ('pastel de carne', 'unidade média', 32.0, 84.0, 5.0, 'Lanches e Pizzas');
INSERT INTO voiceCarbo.alimento VALUES ('pastel de queijo', 'unidade média', 25.0, 75.0, 5.0, 'Lanches e Pizzas');
INSERT INTO voiceCarbo.alimento VALUES ('pastel de queijo de forno', 'unidade grande', 40.0, 185.0, 15.0, 'Lanches e Pizzas');
INSERT INTO voiceCarbo.alimento VALUES ('sanduíche de atum', 'unidade média', 120.0, 372.0, 33.0, 'Lanches e Pizzas');
INSERT INTO voiceCarbo.alimento VALUES ('sanduíche natural', 'unidade média', 120.0, 265.0, 29.0, 'Lanches e Pizzas');
INSERT INTO voiceCarbo.alimento VALUES ('sushi', 'unidade média', 22.0, 57.0, 14.0, 'Lanches e Pizzas');
INSERT INTO voiceCarbo.alimento VALUES ('tapioca pronta', 'unidade pequena', 100.0, 174.0, 43.0, 'Lanches e Pizzas');
INSERT INTO voiceCarbo.alimento VALUES ('torta de frango', 'fatia média', 85.0, 200.0, 16.0, 'Lanches e Pizzas');
INSERT INTO voiceCarbo.alimento VALUES ('torta de sardinha', 'fatia média', 100.0, 217.0, 14.0, 'Lanches e Pizzas');
INSERT INTO voiceCarbo.alimento VALUES ('abacaxi em calda', 'fatia média', 64.0, 78.0, 19.0, 'Doces');
INSERT INTO voiceCarbo.alimento VALUES ('achocolatado em pó diet', '1 colher de sopa', 14.0, 107.0, 10.0, 'Doces');
INSERT INTO voiceCarbo.alimento VALUES ('açúcar cristal', '1 colher de sopa cheia', 24.0, 96.0, 24.0, 'Doces');
INSERT INTO voiceCarbo.alimento VALUES ('açúcar demerara (orgânico)', '1 colher de sopa cheia', 15.0, 60.0, 15.0, 'Doces');
INSERT INTO voiceCarbo.alimento VALUES ('açúcar mascavo', '1 colher de sopa cheia', 19.0, 70.0, 17.0, 'Doces');
INSERT INTO voiceCarbo.alimento VALUES ('ameixa preta em calda', 'unidade média', 42.0, 18.0, 4.0, 'Doces');
INSERT INTO voiceCarbo.alimento VALUES ('arroz-doce', '1 colher de sopa cheia', 40.0, 66.0, 13.0, 'Doces');
INSERT INTO voiceCarbo.alimento VALUES ('bala de goma', 'unidade', 3.0, 11.0, 3.0, 'Doces');
INSERT INTO voiceCarbo.alimento VALUES ('beijinho de coco', 'unidade pequena', 6.0, 25.0, 3.0, 'Doces');
INSERT INTO voiceCarbo.alimento VALUES ('bombom alpino®', 'unidade', 13.0, 70.0, 8.0, 'Doces');
INSERT INTO voiceCarbo.alimento VALUES ('bombom chokito®', 'unidade', 32.0, 141.0, 24.0, 'Doces');
INSERT INTO voiceCarbo.alimento VALUES ('bombom diamante negro®', '3 unidades pequenas', 25.0, 128.0, 16.0, 'Doces');
INSERT INTO voiceCarbo.alimento VALUES ('bombom ferrero rocher®', 'unidade', 12.0, 72.0, 6.0, 'Doces');
INSERT INTO voiceCarbo.alimento VALUES ('bombom ouro branco®', 'unidade', 22.0, 117.0, 13.0, 'Doces');
INSERT INTO voiceCarbo.alimento VALUES ('bombom serenata de amor®', 'unidade', 20.0, 100.0, 13.0, 'Doces');
INSERT INTO voiceCarbo.alimento VALUES ('bombom sonho de valsa®', 'unidade', 22.0, 113.0, 13.0, 'Doces');
INSERT INTO voiceCarbo.alimento VALUES ('bombom talento®', 'unidade', 14.0, 74.0, 8.0, 'Doces');
INSERT INTO voiceCarbo.alimento VALUES ('brigadeiro', 'unidade média', 30.0, 103.0, 16.0, 'Doces');
INSERT INTO voiceCarbo.alimento VALUES ('cajuzinho', 'unidade pequena', 12.0, 44.0, 6.0, 'Doces');
INSERT INTO voiceCarbo.alimento VALUES ('chiclete comum', 'unidade', 5.0, 16.0, 4.0, 'Doces');
INSERT INTO voiceCarbo.alimento VALUES ('chiclete trident®', 'unidade', 2.0, 3.0, 1.0, 'Doces');
INSERT INTO voiceCarbo.alimento VALUES ('chocolate ao leite', 'barra pequena', 30.0, 160.0, 18.0, 'Doces');
INSERT INTO voiceCarbo.alimento VALUES ('chocolate ao leite diet', 'barra pequena', 30.0, 157.0, 13.0, 'Doces');
INSERT INTO voiceCarbo.alimento VALUES ('chocolate baton®', 'unidade', 16.0, 86.0, 10.0, 'Doces');
INSERT INTO voiceCarbo.alimento VALUES ('chocolate bis®', 'unidade', 7.0, 37.0, 5.0, 'Doces');
INSERT INTO voiceCarbo.alimento VALUES ('chocolate meio amargo', 'unidade pequena', 25.0, 128.0, 14.0, 'Doces');
INSERT INTO voiceCarbo.alimento VALUES ('cocada', 'unidade média', 50.0, 185.0, 28.0, 'Doces');
INSERT INTO voiceCarbo.alimento VALUES ('doce de banana', '1 colher de sopa cheia', 48.0, 39.0, 9.0, 'Doces');
INSERT INTO voiceCarbo.alimento VALUES ('doce de batata doce', 'porção pequena', 30.0, 121.0, 22.0, 'Doces');
INSERT INTO voiceCarbo.alimento VALUES ('doce de leite', '1 colher de sopa cheia', 40.0, 116.0, 22.0, 'Doces');
INSERT INTO voiceCarbo.alimento VALUES ('doce de mamão verde', '1 colher de sopa', 40.0, 78.0, 19.0, 'Doces');
INSERT INTO voiceCarbo.alimento VALUES ('flan de baunilha', 'potinho', 100.0, 93.0, 15.0, 'Doces');
INSERT INTO voiceCarbo.alimento VALUES ('flan de baunilha diet', 'potinho', 100.0, 50.0, 7.0, 'Doces');
INSERT INTO voiceCarbo.alimento VALUES ('frutas cristalizadas industrializadas', '1 colher de sopa cheia', 15.0, 48.0, 12.0, 'Doces');
INSERT INTO voiceCarbo.alimento VALUES ('gelatina diet em pó', '1 colher de sopa cheia', 14.0, 1.0, 0.0, 'Doces');
INSERT INTO voiceCarbo.alimento VALUES ('geleia de mocotó', '1 colher de sopa cheia', 40.0, 64.0, 12.0, 'Doces');
INSERT INTO voiceCarbo.alimento VALUES ('goiabada', 'fatia pequena', 40.0, 109.0, 27.0, 'Doces');
INSERT INTO voiceCarbo.alimento VALUES ('manjar', 'fatia média', 90.0, 255.0, 36.0, 'Doces');
INSERT INTO voiceCarbo.alimento VALUES ('maria-mole', 'porção', 44.0, 132.0, 33.0, 'Doces');
INSERT INTO voiceCarbo.alimento VALUES ('mariola', 'unidade', 25.0, 66.0, 16.0, 'Doces');
INSERT INTO voiceCarbo.alimento VALUES ('marmelada', 'fatia média', 60.0, 158.0, 40.0, 'Doces');
INSERT INTO voiceCarbo.alimento VALUES ('marshmallow dr. oetker®', '1 colher de sopa cheia', 10.0, 40.0, 9.0, 'Doces');
INSERT INTO voiceCarbo.alimento VALUES ('mel', '1 colher de sopa', 15.0, 47.0, 12.0, 'Doces');
INSERT INTO voiceCarbo.alimento VALUES ('mousse de chocolate', '1 colher de sopa cheia', 25.0, 79.0, 8.0, 'Doces');
INSERT INTO voiceCarbo.alimento VALUES ('mousse de maracujá', '1 colher de sopa cheia', 35.0, 100.0, 11.0, 'Doces');
INSERT INTO voiceCarbo.alimento VALUES ('nutella®', '1 colher de sopa', 20.0, 106.0, 11.0, 'Doces');
INSERT INTO voiceCarbo.alimento VALUES ('paçoquinha®', 'unidade', 30.0, 125.0, 21.0, 'Doces');
INSERT INTO voiceCarbo.alimento VALUES ('pamonha doce', 'unidade pequena', 130.0, 335.0, 47.0, 'Doces');
INSERT INTO voiceCarbo.alimento VALUES ('pavê de chocolate', 'pedaço médio', 85.0, 154.0, 16.0, 'Doces');
INSERT INTO voiceCarbo.alimento VALUES ('pé de moleque', 'unidade', 17.0, 88.0, 10.0, 'Doces');
INSERT INTO voiceCarbo.alimento VALUES ('pêssego em calda diet', 'unidade pequena', 20.0, 9.0, 2.0, 'Doces');
INSERT INTO voiceCarbo.alimento VALUES ('picolé de frutas kibon®', 'unidade', 63.0, 66.0, 16.0, 'Doces');
INSERT INTO voiceCarbo.alimento VALUES ('pipoca doce', 'saco médio', 20.0, 95.0, 20.0, 'Doces');
INSERT INTO voiceCarbo.alimento VALUES ('pirulito', 'unidade', 20.0, 74.0, 19.0, 'Doces');
INSERT INTO voiceCarbo.alimento VALUES ('pudim de leite condensado', '1 colher de sopa', 50.0, 108.0, 17.0, 'Doces');
INSERT INTO voiceCarbo.alimento VALUES ('quindim', 'unidade média', 35.0, 111.0, 15.0, 'Doces');
INSERT INTO voiceCarbo.alimento VALUES ('rapadura', 'pedaço médio', 55.0, 194.0, 48.0, 'Doces');
INSERT INTO voiceCarbo.alimento VALUES ('sorvete diet', '1 bola', 60.0, 62.0, 10.0, 'Doces');
INSERT INTO voiceCarbo.alimento VALUES ('sorvete*', '1 bola', 60.0, 161.0, 19.0, 'Doces');
INSERT INTO voiceCarbo.alimento VALUES ('suspiro', 'unidade média', 10.0, 38.0, 9.0, 'Doces');
INSERT INTO voiceCarbo.alimento VALUES ('trufa de chocolate', 'unidade grande', 30.0, 140.0, 15.0, 'Doces');
INSERT INTO voiceCarbo.alimento VALUES ('água de coco verde', 'copo duplo', 240.0, 43.0, 10.0, 'Bebidas');
INSERT INTO voiceCarbo.alimento VALUES ('bebida energética red bull®', 'lata', 250.0, 112.0, 28.0, 'Bebidas');
INSERT INTO voiceCarbo.alimento VALUES ('café solúvel em pó', '1 colher de sopa cheia', 4.0, 6.0, 1.0, 'Bebidas');
INSERT INTO voiceCarbo.alimento VALUES ('caldo de cana', 'copo duplo', 240.0, 201.0, 49.0, 'Bebidas');
INSERT INTO voiceCarbo.alimento VALUES ('cappuccino', '1 colher de chá cheia', 8.0, 33.0, 6.0, 'Bebidas');
INSERT INTO voiceCarbo.alimento VALUES ('cerveja', 'lata', 350.0, 143.0, 12.0, 'Bebidas');
INSERT INTO voiceCarbo.alimento VALUES ('cerveja sem álcool', 'lata', 335.0, 89.0, 15.0, 'Bebidas');
INSERT INTO voiceCarbo.alimento VALUES ('chopp escuro', 'tulipa', 290.0, 148.0, 11.0, 'Bebidas');
INSERT INTO voiceCarbo.alimento VALUES ('conhaque', 'dose', 50.0, 115.0, 0.0, 'Bebidas');
INSERT INTO voiceCarbo.alimento VALUES ('champagne (espumante)', 'taça', 100.0, 82.0, 3.0, 'Bebidas');
INSERT INTO voiceCarbo.alimento VALUES ('refrigerante comum', 'copo duplo', 240.0, 96.0, 24.0, 'Bebidas');
INSERT INTO voiceCarbo.alimento VALUES ('refrigerante diet', 'copo duplo cheio', 240.0, 1.0, 0.0, 'Bebidas');
INSERT INTO voiceCarbo.alimento VALUES ('suco ades light®', 'copo duplo', 240.0, 38.0, 8.0, 'Bebidas');
INSERT INTO voiceCarbo.alimento VALUES ('suco de abacaxi com açúcar', 'copo duplo cheio', 240.0, 103.0, 25.0, 'Bebidas');
INSERT INTO voiceCarbo.alimento VALUES ('suco de laranja sem açúcar', 'copo', 200.0, 90.0, 21.0, 'Bebidas');
INSERT INTO voiceCarbo.alimento VALUES ('suco de manga com açúcar', 'copo duplo cheio', 240.0, 96.0, 23.0, 'Bebidas');
INSERT INTO voiceCarbo.alimento VALUES ('suco de maçã', 'copo duplo', 240.0, 120.0, 26.0, 'Bebidas');
INSERT INTO voiceCarbo.alimento VALUES ('suco de maracujá com açúcar', 'copo duplo cheio', 240.0, 70.0, 17.0, 'Bebidas');
INSERT INTO voiceCarbo.alimento VALUES ('suco tang®', 'copo', 200.0, 84.0, 21.0, 'Bebidas');
INSERT INTO voiceCarbo.alimento VALUES ('suco de laranja del valle®', 'copo grande', 300.0, 116.0, 29.0, 'Bebidas');
INSERT INTO voiceCarbo.alimento VALUES ('vinho branco seco', 'taça', 150.0, 99.0, 0.0, 'Bebidas');
INSERT INTO voiceCarbo.alimento VALUES ('vinho branco suave', 'taça', 150.0, 21.0, 5.0, 'Bebidas');
INSERT INTO voiceCarbo.alimento VALUES ('vinho tinto seco', 'taça', 80.0, 58.0, 1.0, 'Bebidas');
INSERT INTO voiceCarbo.alimento VALUES ('vodka', 'medida', 40.0, 126.0, 18.0, 'Bebidas');
INSERT INTO voiceCarbo.alimento VALUES ('azeite de oliva (extra)', '1 colher de sopa cheia', 8.0, 72.0, 0.0, 'Outros');
INSERT INTO voiceCarbo.alimento VALUES ('baião de dois', 'escumadeira cheia', 100.0, 136.0, 20.0, 'Outros');
INSERT INTO voiceCarbo.alimento VALUES ('bobó de camarão', '1 colher de sopa', 28.0, 46.0, 6.0, 'Outros');
INSERT INTO voiceCarbo.alimento VALUES ('caldo verde', '1 concha média cheia', 130.0, 79.0, 7.0, 'Outros');
INSERT INTO voiceCarbo.alimento VALUES ('canja de galinha', '1 concha média cheia', 130.0, 110.0, 12.0, 'Outros');
INSERT INTO voiceCarbo.alimento VALUES ('caruru', '1 colher de sopa', 30.0, 64.0, 1.0, 'Outros');
INSERT INTO voiceCarbo.alimento VALUES ('estrogonofe de frango', '1 colher de sopa cheia', 25.0, 50.0, 0.0, 'Outros');
INSERT INTO voiceCarbo.alimento VALUES ('feijão tropeiro', '1 colher de sopa cheia', 15.0, 50.0, 7.0, 'Outros');
INSERT INTO voiceCarbo.alimento VALUES ('feijoada caseira', '1 concha média cheia', 225.0, 346.0, 24.0, 'Outros');
INSERT INTO voiceCarbo.alimento VALUES ('salada de legumes com maionese', '1 colher de sopa cheia', 35.0, 34.0, 5.0, 'Outros');
INSERT INTO voiceCarbo.alimento VALUES ('salpicão de frango', '1 colher de sopa cheia', 25.0, 61.0, 2.0, 'Outros');
INSERT INTO voiceCarbo.alimento VALUES ('sopa de legumes com carne', '1 concha média', 130.0, 100.0, 8.0, 'Outros');
INSERT INTO voiceCarbo.alimento VALUES ('suflê de legumes', '1 colher de sopa cheia', 55.0, 70.0, 5.0, 'Outros');
INSERT INTO voiceCarbo.alimento VALUES ('vaca atolada', '1 concha média cheia', 100.0, 259.0, 3.0, 'Outros');
INSERT INTO voiceCarbo.alimento VALUES ('vatapá', 'unidade', 100.0, 127.0, 9.0, 'Outros');
